#+title:  DOOM Emacs configuration
#+author: Andrés Núñez
#+STARTUP: showeverything
#+PROPERTY: toc:2
#+PROPERTY: header-args:emacs-lisp :tangle yes :results none


* Literate configuration
Remember to enable
:config
literate

On the DOOM Emacs init.el file in order for this to work. Also, the contents of config.el should be:

;;; config.el -*- lexical-binding: t; -*-

(org-babel-load-file
 (expand-file-name "config.org" doom-user-dir))


Place your private configuration here! Remember, you do not need to run 'doom sync' after modifying this file!

* Identification
Some functionality uses this to identify you, e.g. GPG configuration, email clients, some templates and snippets. It is optional.
#+begin_src emacs-lisp
(setq user-full-name "Andrés Núñez"
      user-mail-address "nunezlopez.ja@gmail.com")
#+end_src

* Theme and other basic UI stuff
#+begin_src emacs-lisp
(setq doom-theme 'doom-gruvbox)
(setq display-line-numbers-type 'relative)
#+end_src

* Font
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "JetBrainsMono Nerd Font" :size 17)
      doom-variable-pitch-font (font-spec :family "JetBrainsMono Nerd Font" :size 16))

#+end_src

* Org, Org agenda, and Org Roam
#+begin_src emacs-lisp
(setq org-directory "~/Nextcloud/Notes/")
(after! org
        (setq org-agenda-files (list org-directory)
       org-roam-directory (expand-file-name "roam" org-directory))
        (setq org-agenda-span 20))
(after! org-roam
 (org-roam-db-autosync-mode)
 (setq org-roam-mode-sections
       (list #'org-roam-backlinks-section
             #'org-roam-reflinks-section
             #'org-roam-unlinked-references-section)))
#+end_src

* Languages and LSP stuff
** C++
#+begin_src emacs-lisp
(after! eglot
  (add-hook 'eglot-managed-mode-hook (lambda () (eglot-inlay-hints-mode -1))))
#+end_src
** Rust
** Odin

* Some notes about Configuring packages from the starter Doom config
 Whenever you reconfigure a package, make sure to wrap your config in an
 `with-eval-after-load' block, otherwise Doom's defaults may override your
 settings. E.g.

   (with-eval-after-load 'PACKAGE
     (setq x y))

 The exceptions to this rule:

   - Setting file/directory variables (like `org-directory')
   - Setting variables which explicitly tell you to set them before their
     package is loaded (see 'C-h v VARIABLE' to look them up).
   - Setting doom variables (which start with 'doom-' or '+').

 Here are some additional functions/macros that will help you configure Doom.

 - `load!' for loading external *.el files relative to this one
 - `add-load-path!' for adding directories to the `load-path', relative to
   this file. Emacs searches the `load-path' when you load packages with
   `require' or `use-package'.
 - `map!' for binding new keys

 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
 This will open documentation for it, including demos of how they are used.
 Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
 etc).

 You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
 they are implemented.

 (use-package odin-ts-mode
   :mode "\\.odin\\'")

 (after! treesit
   (add-to-list 'treesit-language-source-alist
                '(odin "https://github.com/tree-sitter-grammars/tree-sitter-odin")))
